#!/command/with-contenv sh
exec 2>&1

cat > /etc/php84/php-fpm.d/www.conf << 'POOL'
[www]
user = abc
group = abc
listen = /run/php/php-fpm.sock
listen.owner = abc
listen.group = abc
listen.mode = 0660
pm = dynamic
pm.max_children = 10
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
pm.max_requests = 500
php_admin_value[error_log] = /data/log/php/error.log
php_admin_flag[log_errors] = on
POOL

echo "Starting php-fpm..."
exec php-fpm -F
